### ISSUE TITLE
Can't Build nvapihelper

### ISSUE THREAD

**Issue by AshotN** [sharowyeh/NvGpuUtility#1]
I followed all your instructions in the ReadMe but still I get 100+ build errors

**Comment by sharowyeh** [comment]
@AshotN Could you provide more detail about the reported errors?
And the building environment likes NV SDK version and CUDA toolkit version

**Comment by sharowyeh** [comment]
@AshotN Sorry, I forgot most of GPU adjustment features are only for NVIDIA NDA-developer, it's my fault.
You may need to send NDA request for specific edition [here](https://developer.nvidia.com/content/nvapi_request).
