### ISSUE TITLE
how nvml and nvapi version?

### ISSUE THREAD

**Issue by zhuce2022** [sharowyeh/NvGpuUtility#2]
i'm build in nvml(cuda 10.1 or cuda 8.0 ) and nvapi sdk r430 or r440

build error

1>------ 已启动全部重新生成: 项目: nvapihelper, 配置: Debug x64 ------
1>stdafx.cpp
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_common.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_sli.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_stereo.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_d3dext.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>dllmain.cpp
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_common.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_sli.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_stereo.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_d3dext.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salstart.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapi_lite_salend.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>nvapihelper.cpp
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(126): warning C4477: “sprintf_s”: 格式字符串“%x”需要类型“unsigned int”的参数，但可变参数 3 拥有了类型“NvPhysicalGpuHandle”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(126): warning C4313: “sprintf_s”: 格式字符串中的“%x”与“NvPhysicalGpuHandle”类型的参数 3 冲突
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(183): warning C4477: “sprintf_s”: 格式字符串“%x”需要类型“unsigned int”的参数，但可变参数 2 拥有了类型“NvPhysicalGpuHandle”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(183): warning C4313: “sprintf_s”: 格式字符串中的“%x”与“NvPhysicalGpuHandle”类型的参数 2 冲突
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(231): warning C4477: “sprintf_s”: 格式字符串“%p”需要类型“void *”的参数，但可变参数 2 拥有了类型“NV_GPU_CLOCK_FREQUENCIES”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(273): warning C4477: “sprintf_s”: 格式字符串“%p”需要类型“void *”的参数，但可变参数 2 拥有了类型“NV_GPU_CLOCK_FREQUENCIES”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(315): warning C4477: “sprintf_s”: 格式字符串“%p”需要类型“void *”的参数，但可变参数 2 拥有了类型“NV_GPU_CLOCK_FREQUENCIES”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(397): error C2653: “NV_GPU_PERF_PSTATE_CLIENT_LIMIT_ID”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(397): error C2065: “NVAPI_PERF_PSTATE_CLIENT_LIMIT_HARD”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(397): error C3861: “NvAPI_GPU_GetPstateClientLimits”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(402): error C2653: “NV_GPU_PERF_PSTATE_CLIENT_LIMIT_ID”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(402): error C2065: “NVAPI_PERF_PSTATE_CLIENT_LIMIT_SOFT”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(402): error C3861: “NvAPI_GPU_GetPstateClientLimits”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(450): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(450): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(456): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(456): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(476): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(476): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(485): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(485): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(602): error C3861: “NvAPI_GPU_SetPstates20”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(615): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“NV_GPU_PERF_PSTATES20_PARAM_DELTA”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(715): error C3861: “NvAPI_GPU_SetPstates20”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(728): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“NV_GPU_PERF_PSTATES20_PARAM_DELTA”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(821): error C3861: “NvAPI_GPU_SetPstates20”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(834): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“NV_GPU_PERF_PSTATES20_PARAM_DELTA”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(892): error C3861: “NvAPI_GPU_SetPstates20”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(903): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“NV_GPU_PERF_PSTATES20_PARAM_DELTA”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(927): warning C4477: “sprintf_s”: 格式字符串“%p”需要类型“void *”的参数，但可变参数 2 拥有了类型“NV_GPU_DYNAMIC_PSTATES_INFO_EX”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(930): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_GPU”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(931): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_GPU”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(932): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_GPU”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(936): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_FB”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(937): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_FB”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(938): error C2065: “NVAPI_GPU_UTILIZATION_DOMAIN_FB”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(972): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(972): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1021): error C2065: “NV_GPU_GETCOOLER_SETTINGS”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1021): error C2146: 语法错误: 缺少“;”(在标识符“cooler”的前面)
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1021): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1022): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1022): error C2065: “NV_GPU_GETCOOLER_SETTINGS_VER”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1024): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1024): error C3861: “NvAPI_GPU_GetCoolerSettings”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1025): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1025): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1025): note: 占位符和其参数预计 2 可变参数，但提供的却是 1 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1025): note: 缺失的可变参数 2 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1036): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1038): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1038): error C2653: “NV_COOLER_POLICY”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1038): error C2065: “NVAPI_COOLER_POLICY_MANUAL”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): note: 占位符和其参数预计 3 可变参数，但提供的却是 1 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1040): note: 缺失的可变参数 2 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1042): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1042): error C2653: “NV_COOLER_POLICY”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1042): error C2065: “NVAPI_COOLER_POLICY_DEFAULT”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): note: 占位符和其参数预计 3 可变参数，但提供的却是 1 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1044): note: 缺失的可变参数 2 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): warning C4477: “sprintf_s”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“size_t”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): note: 请考虑在格式字符串中使用“%zd”
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): note: 占位符和其参数预计 3 可变参数，但提供的却是 1 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1048): note: 缺失的可变参数 2 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1050): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1052): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1052): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1052): note: 占位符和其参数预计 3 可变参数，但提供的却是 0 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1052): note: 缺失的可变参数 1 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1056): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1056): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1056): note: 占位符和其参数预计 2 可变参数，但提供的却是 0 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1056): note: 缺失的可变参数 1 为格式字符串“%d”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1059): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1059): error C2065: “NVAPI_COOLER_TARGET_GPU”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1060): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1060): error C2065: “NVAPI_COOLER_TARGET_ALL”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1062): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1064): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1065): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1067): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1080): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1081): error C2065: “cooler”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1113): error C2065: “NV_GPU_SETCOOLER_LEVEL”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1113): error C2146: 语法错误: 缺少“;”(在标识符“level”的前面)
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1113): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1114): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1114): error C2065: “NV_GPU_SETCOOLER_LEVEL_VER”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1118): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1118): error C2653: “NV_COOLER_POLICY”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1118): error C2065: “NVAPI_COOLER_POLICY_MANUAL”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1119): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1123): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1123): error C2653: “NV_COOLER_POLICY”: 不是类或命名空间名称
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1123): error C2065: “NVAPI_COOLER_POLICY_DEFAULT”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1125): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1125): error C3861: “NvAPI_GPU_SetCoolerLevels”: 找不到标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1126): error C2065: “level”: 未声明的标识符
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1126): warning C4473: “sprintf_s”: 没有为格式字符串传递足够的参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1126): note: 占位符和其参数预计 3 可变参数，但提供的却是 1 参数
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1126): note: 缺失的可变参数 2 为格式字符串“%x”所需
1>d:\personal\download\nvgpuutility-master\nvapihelper\nvapihelper.cpp(1257): warning C4477: “sprintf_s”: 格式字符串“%p”需要类型“void *”的参数，但可变参数 2 拥有了类型“NV_GET_CURRENT_SLI_STATE_V2”
1>已完成生成项目“nvapihelper.vcxproj”的操作 - 失败。
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

**Comment by sharowyeh** [comment]
@zhuce30hao  R36x or R37x NDA version in middle of 2016 if my memory is correct... 
Since this project has not been updated for a long time, and lack of upgrade plan because it's required nvapi library from NDA developer registration.
I believe newer version of nvapi's functions have been changed a lot, and sadly NV has stopped public NDA developer registration.
If you develop these features for your company, maybe ask manager to contact NVIDIA in official for the help.
